name: Scrape latest hospital data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gitpython sqlite-utils
      
      - name: Fetch latest data
        run: |
          python scrape_hospital_data.py

      - name: Check if hospital_data.json has changed
        id: file_check
        run: |
          git diff --name-only | grep hospital_data.json && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"

      - name: Copy hospital_data.json with timestamp if changed
        if: steps.file_check.outputs.changed == 'true'
        run: |
          mkdir -p data
          timestamp=$(date -u +'%Y%m%d%H%M%S')
          cp hospital_data.json data/hospital_data_${timestamp}.json
          git add data/hospital_data_${timestamp}.json

      - name: Commit and push if it changed
        if: steps.file_check.outputs.changed == 'true'
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Latest hospital data: $(date -u)"
          git push





