name: Scrape latest hospital data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Fetch latest data
        run: |
          python scrape_hospital_data.py
      
      - name: Validate hospital data changes
        run: |
          python validate1.py
          # Ensure the directory exists before trying to write to validate.txt
          mkdir -p data
          # Assuming validate1.py writes its output to stdout, redirect it to data/validate.txt
          python validate1.py > data/validate.txt

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add hospital_data.json data/validate.txt
          timestamp=$(date -u)
          git commit -m "Latest hospital data and validation: ${timestamp}" || exit 0
          git push




